const ITEM_COMPLETED = 'completed';
const ITEM_PROGRESS = 'progress';

const FILTER_TODO_ALL = 'all';
const FILTER_TODO_COMPLETED = 'completed';
const FILTER_TODO_PROGRESS ='progress';

const TODO_COLOR = "rgb(0, 0, 0)";

export {ITEM_COMPLETED, ITEM_PROGRESS, FILTER_TODO_ALL, FILTER_TODO_COMPLETED, FILTER_TODO_PROGRESS, TODO_COLOR}